### ISSUE TITLE
I'm just getting white squares

### ISSUE THREAD

**Issue by nigelatdas** [tumic0/pbf2png#1]
Hi. 
Great project. 
When I run the tool against my MVT tiles I get white png files. :(
What am I doing wrong? 

Here is an example file. 
[9_461_313.zip](https://github.com/tumic0/pbf2png/files/12654193/9_461_313.zip)

They are in standard Mapbox format (I believe).

I was wondering if it's just that I need to add my own styling. 
I have Mapbox Bright styles in ~/.local/share/pbf2png/styles/

I want them to be loadable instead of the vector tiles when I zoom out on the map... so I want the background transparent and the boarders black. 

Any help you can give is very muchly appreciated. 

Is there some way to turn on more debugging information so I can be sure it's finding `protoc` etc correctly?

**Comment by tumic0** [comment]
I don't know where you got your data, but it is evidently not Mapbox-style MVT data. A sample of Mapbox-style MVT data as used in the [Mapbox GPXSee map](https://github.com/tumic0/GPXSee-maps/blob/master/World/Mapbox.tpl) is attached. If you use the appropriate [style](https://github.com/tumic0/QtPBFImagePlugin-styles/tree/master/Mapbox/bright) you will get a "nice" PNG tile when running `pbf2png` over the directory.

![6-34-21](https://github.com/tumic0/pbf2png/assets/11480505/b3e8f514-d718-4187-ad72-ed1b08f65631)
[6-34-21.mvt.gz](https://github.com/tumic0/pbf2png/files/12659322/6-34-21.mvt.gz)

**Comment by tumic0** [comment]
> I have Mapbox Bright styles in ~/.local/share/pbf2png/styles/

That's also wrong, the directory must be `~/.local/share/pbf2png/style/`
